#!/usr/bin/env bash

if [[ ! -d reveal.js ]]; then
  echo "Downloading reveal.js"
  wget -c https://github.com/hakimel/reveal.js/archive/3.8.0.tar.gz  -O - | tar xz
  mv reveal.js-3.8.0/ reveal.js/
else
  echo "reveal.js is already downloaded, nothing to do"
fi
